import config as cfg

class SpecialCharacters:
    ESCAPE_CHARACTER = cfg.ESCAPE_CHARACTER
    STRING_MARKER = cfg.STRING_MARKER
    OPEN_BRACKET = cfg.OPEN_BRACKET
    CLOSE_BRACKET = cfg.CLOSE_BRACKET
    OPEN_SQUARE_BRACKET = cfg.OPEN_SQUARE_BRACKET
    CLOSE_SQUARE_BRACKET = cfg.CLOSE_SQUARE_BRACKET
    ASSIGNMENT_OPERATOR = cfg.ASSIGNMENT_OPERATOR
    COMMENT_MARKER = cfg.COMMENT_MARKER
    ENDLINE_MARKER = cfg.ENDLINE_MARKER
    ARGUMENT_SEPARATOR = cfg.ARGUMENT_SEPARATOR
    DECLARE_NEGATIVE_NUMBER_OPERATOR = cfg.DECLARE_NEGATIVE_NUMBER_OPERATOR